site_name: SLISEMAP
site_url: https://edahelsinki.github.io/slisemap
repo_url: https://github.com/edahelsinki/slisemap
edit_uri: ""

theme:
  name: material
  icon:
    logo: material/book-open
  favicon: ""
  font: false
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: deep purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.sections
    # - navigation.indexes

nav:
  - Get started:
      - Introduction: index.md
      - Examples: https://github.com/edahelsinki/slisemap/tree/main/examples
      - Presentation:
          - Video: https://youtu.be/zvcFYItwRlQ
          - Slides: https://github.com/edahelsinki/slisemap/blob/main/examples/demo_presentation.pdf
  - Documentation:
      - slisemap: slisemap.md
      - slisemap.slisemap: slisemap.slisemap.md
      - slisemap.slipmap: slisemap.slipmap.md
      - slisemap.local_models: slisemap.local_models.md
      - slisemap.utils: slisemap.utils.md
      - slisemap.metrics: slisemap.plot.md
      - slisemap.escape: slisemap.escape.md
      - slisemap.tuning: slisemap.tuning.md
      - slisemap.metrics: slisemap.metrics.md
      - slisemap.diagnostics: slisemap.diagnostics.md
  - Links:
      - GitHub: https://github.com/edahelsinki/slisemap
      - PyPI: https://pypi.org/project/slisemap/
      - Paper (Slisemap): https://doi.org/10.1007/s10994-022-06261-1
      - Demo Paper: https://doi.org/10.1007/978-3-031-26422-1_41

plugins:
  # - offline
  - search
  - privacy:
      assets: false
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            group_by_category: False
            show_root_heading: True
  - include-markdown
