# This workflow will make the documentation using sphinx and push it to the gh-pages branch when a release is created
# For more information see: https://www.sphinx-doc.org/en/master/tutorial/deploying.html#id5

name: Build documentation

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
        if [ -f docs/requirements.txt ]; then python -m pip install -r docs/requirements.txt; fi
    - name: Build HTML
      run: |
        cd docs
        make html -e
    - name: Deploy
      uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
