# This workflow will build the documentation using mkdocs and push it to the gh-pages branch when a release is created
# For more information see: https://www.mkdocs.org/user-guide/deploying-your-docs/

name: docs

on:
  workflow_dispatch:
  release:
    branches: [master, main]
    types: [released]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install dependencies
      run:  |
        python -m pip install --upgrade pip
        python -m pip install -r docs/requirements-dev.txt
        
    - name: Build and deploy
      run: mkdocs gh-deploy --force --clean --verbose
